import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { BlogData } from '@/data/products'

const Blog = () => {
	return (
		<>
			<Head>
				<title>Blog</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1 className='text-4xl font-bold text-center mt-20'>Blog</h1>

			<div className='w-[80%] mx-auto mt-6 grid grid-cols-3 gap-6'>
				{BlogData.map((item, index) => {
					return (
						<>
							<div className='bg-white' key={index}>
								<div className=' overflow-hidden relative w-full '>
									<Image
										src={item.image}
										alt='logo'
										width={300}
										height={250}
										className='w-full h-60 object-cover  duration-500 hover:scale-[1.1]'
									></Image>
								</div>

								<h2 className='ml-4 mt-4 font-semibold text-xl'>
									{item.title}
								</h2>
								<div className='ml-4 py-4 font-normal text-base'>
									<p>{item.text}</p>
								</div>
							</div>
						</>
					)
				})}
			</div>
		</>
	)
}

export default Blog
