import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Link from 'next/link'
import NameFont from '@/components/MenuFonts/NameFont'

import { BsSearch } from 'react-icons/bs'
import { useState } from 'react'
import MenuFont from '@/components/MenuFonts/MenuFont'
import ProductFont from '@/components/ProductFont'

function Home({ Data }) {
	const [HomeData, setHomeData] = useState(Data)
	const funcFilter = nameFont => {
		const nameFonts = Data.filter(item => item.nameFont === nameFont)
		setHomeData(nameFonts)
	}

	const [seeMore, setSeeMore] = useState(8)

	const showMore = HomeData.slice(0, seeMore)

	const loadMore = () => {
		setSeeMore(prevValue => prevValue + 4)
	}

	return (
		<>
			<Head>
				<title>sanFont</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{/* search */}
			<div className=' w-full mt-12'>
				<div className='relative mx-auto w-[70%] max-lg:w-[80%]'>
					<input
						type='text'
						id='small-input'
						placeholder='Tìm font tại đây'
						className='pl-4 font-normal w-full py-3 border border-white hover:border-oranges rounded-[30px] focus:outline-none focus:border-oranges text-base '
					/>

					<div className='absolute top-3 right-6'>
						<BsSearch className='w-7 h-6 text-[#9ca3af]' />
					</div>
				</div>
			</div>

			{/* Menu font */}
			<MenuFont Data={Data} setHomeData={setHomeData} />

			{/* products */}

			<div className='flex gap-3'>
				<h2 className='font-medium text-3xl ml-[7%] mt-16'>
					{HomeData.length} font
				</h2>
			</div>

			<div className='w-[85%]	 mx-auto mt-6 grid grid-cols-4 gap-6 max-2xl:w-[95%] max-lg:grid-cols-2 max-sm:grid-cols-1'>
				{showMore.map((item, id) => {
					return (
						// <div className='bg-[#ffffff] shadow-md' key={id}>
						// 	<div
						// 		htmlFor='my-modal-4'
						// 		className='cursor-pointer overflow-hidden relative '
						// 	>
						// 		<Image
						// 			src={item.image}
						// 			alt='logo'
						// 			width={300}
						// 			height={250}
						// 			className=' w-full h-44 object-cover duration-500 hover:scale-[1.1]'
						// 		></Image>

						// 		<button className='demo absolute bg-[#ff0000] py-[3px] px-[6px] text-[#ffffff] text-xs rounded-br-lg  z-30'>
						// 			<Link className='' href='' legacyBehavior>
						// 				<a className='font-bold '>Lưu</a>
						// 			</Link>
						// 		</button>
						// 	</div>

						// 	<Link href={`/fontVH/${item.id}`}>
						// 		<h2 className='ml-3 mt-4 font-semibold text-[#000000] text-base'>
						// 			{item.title}
						// 		</h2>
						// 	</Link>
						// 	<div className='ml-3 py-4 font-normal text-xs leading-6 text-[#818181]'>
						// 		<p>
						// 			<span className='font-bold'>Tác giả:</span>
						// 			{item.author}
						// 		</p>
						// 		<p>
						// 			<span className='font-bold'>Người đăng:</span>
						// 			{item.user}
						// 		</p>
						// 		<p>
						// 			<span className='font-bold'>Việt hóa :</span>
						// 			{item.translate}
						// 		</p>
						// 		<p>
						// 			<span className='font-bold'>Ngày đăng:</span>
						// 			{item.date}
						// 		</p>
						// 		<p>
						// 			<span className='font-bold'>Số lượt tải font:</span>
						// 			{item.quantity}
						// 		</p>
						// 	</div>
						// 	<div className=' text-sm text-center bg-oranges hover:bg-[#ff0000] cursor-pointer py-3 text-white'>
						// 		<Link href='/' legacyBehavior>
						// 			<a className='font-medium'>TẢI FONT NÀY NGAY</a>
						// 		</Link>
						// 	</div>
						// </div>
						<div className='bg-white shadow-md' key={id}>
							<div className='relative'>
								<div className=' group overflow-hidden'>
									<div className=' cursor-pointer  duration-500 hover:scale-[1.1] relative '>
										<label htmlFor='my-modal-3' className=' '>
											<Image
												src={item.image}
												alt='logo'
												width={300}
												height={250}
												className=' w-full h-44 object-cover '
											></Image>
											<div className='w-full h-44 absolute top-0 bg-black/60  duration-500  opacity-0 group-hover:opacity-100 '>
												<h2 className='text-white text-center text-lg font-semibold mt-[25%] '>
													XEM DEMO
												</h2>
											</div>
										</label>
									</div>
								</div>

								<input
									type='checkbox'
									id='my-modal-3'
									className=' modal-toggle'
								/>
								<div className='modal rounded-none'>
									<div className='modal-box relative '>
										<label
											htmlFor='my-modal-3'
											className='btn btn-sm btn-circle absolute right-2 top-2'
										>
											✕
										</label>
										<div>
											<Image
												src={item.image}
												alt='img'
												width={800}
												height={800}
												className='w-[99%]  object-cover  '
											></Image>
										</div>
									</div>
								</div>

								<button className='demo absolute bg-[#ff0000] py-[3px] px-[6px] text-white text-xs rounded-br-lg  z-1'>
									<Link className='' href='' legacyBehavior>
										<a className='font-bold '>Lưu</a>
									</Link>
								</button>
							</div>
							<Link href={`/fontVH/${item.id}`}>
								<h2 className='ml-3 mt-4 font-semibold text-base text-[#000000]'>
									{item.title}
								</h2>
							</Link>
							<div className='ml-3 py-4 font-normal text-xs leading-6 text-[#818181]'>
								<p>
									<span className='font-bold'>Tác giả:</span>
									{item.author}
								</p>
								<p>
									<span className='font-bold'>Người đăng:</span>
									{item.user}
								</p>
								<p>
									<span className='font-bold'>Việt hóa :</span>
									{item.translate}
								</p>
								<p>
									<span className='font-bold'>Ngày đăng:</span>
									{item.date}
								</p>
								<p>
									<span className='font-bold'>Số lượt tải font:</span>
									{item.quantity}
								</p>
							</div>
							<div className=' text-sm text-center bg-oranges hover:bg-[#ff0000] cursor-pointer py-3 text-white'>
								<Link href='/' legacyBehavior>
									<a className='font-medium'>TẢI FONT NÀY NGAY</a>
								</Link>
							</div>
						</div>
					)
				})}
			</div>

			{/* Xem thêm */}
			<div className='w-full text-center mt-6'>
				<button
					onClick={loadMore}
					className='bg-oranges  hover:bg-[#ff0000] py-2 px-6 font-normal text-base text-white rounded-[8px]'
				>
					Xem thêm
				</button>
			</div>

			<div className='w-[85%] h-96 bg-white mx-auto mt-12'></div>
		</>
	)
}

export default Home

export async function getStaticProps() {
	const response = await fetch('http://localhost:4000/HomeData')
	const data = await response.json()

	return {
		props: {
			Data: data,
		},
	}
}
