import Head from 'next/head'

const fontVH = () => {
	return (
		<>
			<Head>
				<title>Font việt hóa</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>font vieet hoas</h1>
		</>
	)
}

export default fontVH
