import Head from 'next/head'
import React, { useState } from 'react'
import { FaLongArrowAltLeft } from 'react-icons/fa'
import { FaLongArrowAltRight } from 'react-icons/fa'
import ProductFont from '@/components/ProductFont'

const fontVH = ({ categoryFont }) => {
	return (
		<>
			<Head>
				<title>Font việt hóa</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h2 className='font-medium text-3xl ml-[10%] mt-16'>
				Font việt hóa ( {categoryFont.length} font){' '}
			</h2>

			<div className='w-[85%]	 mx-auto mt-10 grid grid-cols-4 gap-6  max-2xl:w-[95%] max-lg:grid-cols-2 max-sm:grid-cols-1'>
				<ProductFont categoryFont={categoryFont} />
			</div>

			<div className='text-center justify-center mt-6'>
				<ul class='inline-flex items-center -space-x-px gap-2 '>
					<li className='p-3 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						<FaLongArrowAltLeft />
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						1
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						2
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						3
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						4
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						5
					</li>
					<li className='px-4 py-2 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						6
					</li>

					<li className='p-3 rounded-sm cursor-pointer bg-white text-black hover:bg-[#c4c4c4] focus:bg-[#c4c4c4]'>
						<FaLongArrowAltRight />
					</li>
				</ul>
			</div>
		</>
	)
}

export default fontVH

export async function getStaticProps() {
	const response = await fetch(`http://localhost:4000/HomeData`)
	const data = await response.json()

	const datas = data.filter(e => e.category === 'FontVH')

	return {
		props: {
			categoryFont: datas,
		},
	}
}
